from fastapi import APIRouter, HTTPException
from services.optimize import PromptOptimizer
from services.energy_calculation import TokenEnergyCalculator
from services.llm_optimize import get_llm_optimizer
from dto.optimize_prompt_dto import PromptRequest, EnergySavedResponse

optimize_router = APIRouter(tags=["Prompt Optimize"])


# ---------------------------------------------------------------------------
# Existing NLTK rule-based endpoint — unchanged
# ---------------------------------------------------------------------------

@optimize_router.post("/optimize")
def optimize_prompt(prompt: PromptRequest):
    energy_calculator = TokenEnergyCalculator()
    original_prompt_energy = energy_calculator.analyze_prompt(prompt=prompt.text, model=prompt.model_name)
    prompt_optimizer = PromptOptimizer()
    response = prompt_optimizer.analyze_prompt(prompt=prompt.text)
    balanced_prompt_energy = energy_calculator.analyze_prompt(prompt=response.balanced, model=prompt.model_name)
    aggresive_prompt_energy = energy_calculator.analyze_prompt(prompt=response.aggressive, model=prompt.model_name)
    conservative_prompt_energy = energy_calculator.analyze_prompt(prompt=response.conservative, model=prompt.model_name)
    energy_saved_balanced = original_prompt_energy.energy_mwh - balanced_prompt_energy.energy_mwh
    energy_saved_aggresive = original_prompt_energy.energy_mwh - aggresive_prompt_energy.energy_mwh
    energy_saved_conservative = original_prompt_energy.energy_mwh - conservative_prompt_energy.energy_mwh
    response_energy = EnergySavedResponse(
        original=response.original,
        conservative=response.conservative,
        aggressive=response.aggressive,
        balanced=response.balanced,
        removed_clauses=response.removed_clauses,
        text_after_clause_removal=response.text_after_clause_removal,
        pos_analysis=response.pos_analysis,
        stopwords_found=response.stopwords_found,
        important_words=response.important_words,
        energy_saved_balanced=energy_saved_balanced,
        energy_saved_aggressive=energy_saved_aggresive,
        energy_saved_conservative=energy_saved_conservative,
        original_energy=original_prompt_energy.energy_mwh,
        co2emission_conservative=conservative_prompt_energy.co2_grams,
        co2emission_aggresive=aggresive_prompt_energy.co2_grams,
        co2emission_balanced=balanced_prompt_energy.co2_grams,
        co2emission_original=original_prompt_energy.co2_grams,
    )
    return response_energy


# ---------------------------------------------------------------------------
# New Phi-3 LLM-based endpoints
# ---------------------------------------------------------------------------

@optimize_router.get("/optimize/ai/status")
def ai_optimizer_status():
    """Check whether the Phi-3 model has been loaded successfully."""
    llm = get_llm_optimizer()
    return {"loaded": llm.loaded, "model": llm.MODEL_NAME}


@optimize_router.post("/optimize/ai")
def optimize_prompt_ai(prompt: PromptRequest):
    """
    LLM-powered prompt optimization using microsoft/Phi-3-mini-4k-instruct.
    Returns the same EnergySavedResponse shape as /optimize, but the
    conservative / balanced / aggressive variants are generated by Phi-3
    rather than NLTK rules.
    """
    llm = get_llm_optimizer()
    if not llm.loaded:
        raise HTTPException(
            status_code=503,
            detail="Phi-3 model is not loaded. Check /optimize/ai/status for details.",
        )

    variants = llm.optimize(prompt.text)
    energy_calculator = TokenEnergyCalculator()

    original_energy     = energy_calculator.analyze_prompt(prompt=prompt.text,               model=prompt.model_name)
    conservative_energy = energy_calculator.analyze_prompt(prompt=variants["conservative"],   model=prompt.model_name)
    balanced_energy     = energy_calculator.analyze_prompt(prompt=variants["balanced"],       model=prompt.model_name)
    aggressive_energy   = energy_calculator.analyze_prompt(prompt=variants["aggressive"],     model=prompt.model_name)

    return EnergySavedResponse(
        original=prompt.text,
        conservative=variants["conservative"],
        balanced=variants["balanced"],
        aggressive=variants["aggressive"],
        # These fields are NLTK-specific; not applicable for LLM path
        removed_clauses="N/A (LLM optimizer)",
        text_after_clause_removal="N/A (LLM optimizer)",
        pos_analysis="N/A (LLM optimizer)",
        stopwords_found="N/A (LLM optimizer)",
        important_words="N/A (LLM optimizer)",
        energy_saved_balanced=original_energy.energy_mwh    - balanced_energy.energy_mwh,
        energy_saved_aggressive=original_energy.energy_mwh  - aggressive_energy.energy_mwh,
        energy_saved_conservative=original_energy.energy_mwh - conservative_energy.energy_mwh,
        original_energy=original_energy.energy_mwh,
        co2emission_original=original_energy.co2_grams,
        co2emission_conservative=conservative_energy.co2_grams,
        co2emission_balanced=balanced_energy.co2_grams,
        co2emission_aggresive=aggressive_energy.co2_grams,
    )
